application:
    environment:
        php:
            version: 5.6.9
build:
    filter:
        excluded_paths: [vendor/*, test/*]
checks:
    php: true

tools:
    external_code_coverage: false
    php_mess_detector: true
    php_code_sniffer: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, test]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, test]
